POST https://login.microsoftonline.com/{{Tenant_Id}}/oauth2/v2.0/token

client_id={{Client_Id}}
&client_secret={{Client_Secret}}
&grant_type=client_credentials
&scope={{Scope}}

####
#@N9.Api_HostAddress = http://localhost:5295
#
#GET {{N9.Api_HostAddress}}/api/books/
#Accept: application/json

####
