name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SOLUTION: '**/*.sln'
  BUILD_CONFIG: 'Release'
  APP_NAME: 'poc-cporal-api-dev-app'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    name: Prepare/Build Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore NuGet Packages
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: Run Tests
        run: |
          dotnet test '**/tests/**/*.csproj' \
            --configuration ${{ env.BUILD_CONFIG }} \
            /p:ExcludeByFile="**/*Migrations/*cs" \
            --collect:"Code Coverage;Format=cobertura"

      - name: Publish Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/**/*.cobertura.xml

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION }} \
          --configuration ${{ env.BUILD_CONFIG }} \
          --no-restore \
          --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: $ {{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
